name: Prefect Deploy
on:
  workflow_dispatch:
    inputs:
      pattern:
        description: "Flow Name Pattern? (defaults to all)"
        required: false
        default: ".*"
jobs:
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find projects -name '*.deployment.py' | grep "${{ github.event.inputs.pattern }}" | jq -Rsc '. / "\n" - [""]')"
  register-flows:
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deployment-file: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
      max-parallel: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Install prefect
        run: pip install prefect adlfs
      - name: Check Prefect version
        run: prefect version
      - name: Login to Prefect Cloud 2.0
        run: |
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }} 
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}
      - name: Create deployment
        working-directory: ${{ matrix.flow-folder }}
        run: |
          cd dirname ${{ matrix.deployment-file }}
          python $(basename ${{ matrix.deployment-file }})
